### ISSUE TITLE
toml_edit: cannot get and unwrap fields?..

### ISSUE THREAD

**Issue by busticated** [toml-rs/toml#622]
hey there 👋 

thanks for these super-helpful crates 🙏  i'm seeing something strange - could very well be user error:

```rust
use std::fs;
use toml_edit::Document;

fn main() {
        let text = fs::read_to_string("../Cargo.toml").unwrap();
        let toml = text.parse::<Document>().unwrap();
        // uncomment the next line to reproduce the error
        // toml.get("package").unwrap();
        let v = match toml.get("package") {
            Some(x) => match x.get("version") {
                Some(v) => v.to_string(),
                None => "failed to get `version`".to_string(),
            },
            None => "failed to get `package`".to_string(),
        };
        println!("GOT VERSION: {:?}", v);
}
```

if you try to call `.unwrap()` after get'ing the `"package"` field, you get an error:

```
thread 'main' panicked at my-project/src/main.rs:7:29:
called `Option::unwrap()` on a `None` value
```

...and yet when `match`'ing, you get the expected value 🤔 

i'm using `toml_edit@v0.20.2`:

```
>>cargo add toml_edit --package xtask
    Updating crates.io index
      Adding toml_edit v0.20.2 to dependencies.
             Features:
             - perf
             - serde
             - unbounded
```

is that expected behavior? any and all suggestions are much appreciated 👍

**Comment by epage** [comment]
I just tried this on the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=71cf473926b371a1bb12fff123f47e51) and didn't see the panic

**Comment by busticated** [comment]
> I just tried this on the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=71cf473926b371a1bb12fff123f47e51) and didn't see the panic

wild! i didn't either. still seeing the error locally of course. admittedly, the actual code is a bit more complex but not terribly - it's a method in a struct that returns `Result<Table, DynError>` (vs. `main` fn) and i have both the `toml` and `toml_edit` crates in play but otherwise the same. here's a backtrace in case that sheds some light. i don't even know how it could happen 🤷 👻 💀 

thanks for taking a look 🙏 

<details>
  <summary>Backtrace (click to expand)</summary>

  ```
thread 'main' panicked at xtask/src/toml.rs:35:29:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x10671bb0b - std::backtrace_rs::backtrace::libunwind::trace::h9283b95ff3ea079b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10671bb0b - std::backtrace_rs::backtrace::trace_unsynchronized::h43b06ae070f7c94c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10671bb0b - std::sys_common::backtrace::_print_fmt::ha0fdd24cac6a3474
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10671bb0b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h65343ad3a85b4e34
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10673e77b - core::fmt::rt::Argument::fmt::h3ec1454c0b08cc5d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:        0x10673e77b - core::fmt::write::h11839d3825cb5605
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:        0x10671896e - std::io::Write::write_fmt::h3ab12d369399333c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:        0x10671b8e9 - std::sys_common::backtrace::_print::ha606478736c0e683
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10671b8e9 - std::sys_common::backtrace::print::h405f7c76ca12eb27
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x10671d7b5 - std::panicking::default_hook::{{closure}}::hed87c355606e1822
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:        0x10671d4e1 - std::panicking::default_hook::hdf696ec8ea0d65aa
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:        0x10671dd20 - std::panicking::rust_panic_with_hook::h7c5059af1af54377
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:        0x10671dc02 - std::panicking::begin_panic_handler::{{closure}}::hd658b0e1cffe3d4d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  13:        0x10671bfe9 - std::sys_common::backtrace::__rust_end_short_backtrace::h3d7834d0cea60a50
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:        0x10671d96d - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:        0x10674e803 - core::panicking::panic_fmt::ha9964785de0afb40
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:        0x10674e897 - core::panicking::panic::h604fa998dd50d7a6
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
  17:        0x106352abe - core::option::Option<T>::unwrap::h7addcf2dad0ab6fe
  18:        0x10632bdd7 - xtask::toml::Toml::read::hc7c409c1c7a3f899
  19:        0x10632c169 - xtask::toml::Toml::load::hd543f31fa4934829
  20:        0x10632bb5a - xtask::toml::Toml::from_path::h451fa1f616f9ab44
  21:        0x106314a01 - xtask::workspace::Workspace::from_path::h1bc0fca5d9ef3f79
  22:        0x10635310b - xtask::try_main::h27d9de7f90b250a7
  23:        0x106352de0 - xtask::main::h49014d644f8701fe
  24:        0x10631f71a - core::ops::function::FnOnce::call_once::h04c19aaab50a7c66
  25:        0x106342e39 - std::sys_common::backtrace::__rust_begin_short_backtrace::h90a884d41c77ecb7
  26:        0x10633ce1c - std::rt::lang_start::{{closure}}::hec6ff67b5492514b
  27:        0x10671324a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcfff0e1d84ed81c5
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  28:        0x10671324a - std::panicking::try::do_call::hbabf83ee9c686a7b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  29:        0x10671324a - std::panicking::try::he3e9a1c93c50f591
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  30:        0x10671324a - std::panic::catch_unwind::ha18733e497b82774
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  31:        0x10671324a - std::rt::lang_start_internal::{{closure}}::hfb6977160fe64fc0
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  32:        0x10671324a - std::panicking::try::do_call::h385fcb260f1f324b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  33:        0x10671324a - std::panicking::try::h3734e87bdbb1b067
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  34:        0x10671324a - std::panic::catch_unwind::hc13dbc187cd64fe1
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  35:        0x10671324a - std::rt::lang_start_internal::h54faea1e36783632
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  36:        0x10633cdf8 - std::rt::lang_start::h490934664bc2ebe3
  37:        0x106354d68 - _main
  38:     0x7ff81014941f - <unknown>
  ```

</details>

`rustc -V`: `rustc 1.73.0 (cc66ad468 2023-10-03)`

**Comment by busticated** [comment]
fwiw, i pushed out a WIP branch showing the issue:

https://github.com/busticated/rusty/tree/tmp/toml-unwrap-weirdness

here's the commit:

https://github.com/busticated/rusty/commit/11dd3d68e08ef1822323020243e5b8d55378d7cc

to repro:

1. follow the installation instructions [here](https://github.com/busticated/rusty#installation)
2. uncomment the [line in question](https://github.com/busticated/rusty/blob/11dd3d68e08ef1822323020243e5b8d55378d7cc/xtask/src/toml.rs#L35)
3. run `cargo xtask crate:list`

you should see:

```
thread 'main' panicked at xtask/src/toml.rs:35:29:
called `Option::unwrap()` on a `None` value
```

if not, well then the mystery deepens i guess 😵‍💫

**Comment by epage** [comment]
When I run it with the line commented out, I get this output
```
GOT VERSION: "nope!"
::::::::::::::::::::::
:::: Running Task ::::
::::::::::::::::::::::
Name: crate:list
Args: []

::::::::::::::::::::::::::
:::: Available Crates ::::
::::::::::::::::::::::::::

GOT VERSION: " \"0.1.0\""
GOT VERSION: " \"0.1.0\""
* detect-newline-style [lib]
  ?? Determine a string's preferred newline character
  >> /home/epage/src/personal/dump/rusty/crates/detect-newline-style

* node-js-release-info [lib]
  ?? Asynchronously retrieve Node.js release info by version and platform from the [downloads server](https
://nodejs.org/download/release/)
  >> /home/epage/src/personal/dump/rusty/crates/node-js-release-info


:::: Done!
```

The `nope` means that it would have panic in that case, so everything seems to be working as expected.

**Comment by busticated** [comment]
😳😅🤦‍♂️

ahhh... lol jeeze. ok, i see it now. ooof. well, thanks a bunch for the 2nd set of eyes and apologies for the noise 🙏👍
